/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.PersistenciaJPA;
import java.util.List;
import javax.swing.JOptionPane;
import model.Modelo;
import model.Pessoa;
import model.VeiOficial;
import model.Veiculo;

/**
 *
 * @author igor
 */
public class TelaCadastroVeiculo extends javax.swing.JFrame {
    PersistenciaJPA persistenciaJPA;
    private Veiculo veiculo; // Declaração da variável veiculo

    /**
     * Creates new form TelaCadastroVeiculo
     */
public TelaCadastroVeiculo(Veiculo veiculo) {
     initComponents();
     this.veiculo = veiculo;
     persistenciaJPA = new PersistenciaJPA();
          carregarModelos();
     carregarPessoas();
     configurarCamposOficiais();
     // Preenche os campos com os dados do veículo
     preencherCampos(veiculo);
}

private void preencherCampos(Veiculo veiculo) {
    if (veiculo != null) {
        // Preenche os campos com os dados do veículo
        txfPlaca.setText(veiculo.getPlaca());
        
        // Preenche o campo Modelo
        cmbModelo.setSelectedItem(veiculo.getModelo());
        
        // Preenche o campo Proprietário
        cmbPessoasCadastradas.setSelectedItem(veiculo.getProprietario());
        
        // Se for um veículo oficial, habilita os campos de Chassi e Renavam
        if (veiculo instanceof VeiOficial) {
            cbxVeiculoOficial.setSelected(true);
            txfChassi.setText(((VeiOficial) veiculo).getChassi());
            txfRenavam.setText(((VeiOficial) veiculo).getRenavan());
            txfChassi.setEnabled(true);
            txfRenavam.setEnabled(true);
        } else {
            cbxVeiculoOficial.setSelected(false);
            txfChassi.setText("");
            txfRenavam.setText("");
            txfChassi.setEnabled(false);
            txfRenavam.setEnabled(false);
        }
    }
}

public TelaCadastroVeiculo() {
     persistenciaJPA = new PersistenciaJPA();
     initComponents();
     carregarModelos();
     carregarPessoas();
     configurarCamposOficiais();
     preencherCampos(veiculo);
}

private void carregarModelos() {
    List<Modelo> modelos = persistenciaJPA.getEntityManager().createQuery("SELECT m FROM Modelo m", Modelo.class).getResultList();
    cmbModelo.removeAllItems();
    for (Modelo modelo : modelos) {
        cmbModelo.addItem(modelo);
    }
}


    private void carregarPessoas() {
        List<Pessoa> pessoas = persistenciaJPA.getEntityManager().createQuery("SELECT p FROM Pessoa p", Pessoa.class).getResultList();
        cmbPessoasCadastradas.removeAllItems();
        for (Pessoa pessoa : pessoas) {
            cmbPessoasCadastradas.addItem(pessoa);
        }
    }

    private void configurarCamposOficiais() {
        cbxVeiculoOficial.addActionListener(evt -> {
            boolean isOficial = cbxVeiculoOficial.isSelected();
            txfChassi.setEnabled(isOficial);
            txfRenavam.setEnabled(isOficial);

            if (!isOficial) {
                txfChassi.setText("");
                txfRenavam.setText("");
            }
        });

        // Inicialmente desativa os campos RENAVAM e CHASSI
        txfChassi.setEnabled(false);
        txfRenavam.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPessoasCadastradas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbModelo = new javax.swing.JComboBox<>();
        cbxVeiculoOficial = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfChassi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfRenavam = new javax.swing.JTextField();
        btnCadastroModelo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btcCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txfPlaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proprietrio´");

        cmbPessoasCadastradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPessoasCadastradasActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo");

        cmbModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModeloActionPerformed(evt);
            }
        });

        cbxVeiculoOficial.setText("É VEICULO oficial?");
        cbxVeiculoOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVeiculoOficialActionPerformed(evt);
            }
        });

        jLabel3.setText("Veiculo Oficial");

        jLabel4.setText("Chassi");

        jLabel5.setText("Renavam");

        btnCadastroModelo.setText("+");
        btnCadastroModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroModeloActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btcCancelar.setText("Cancelar");
        btcCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Palaca");

        txfPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfPlacaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btcCancelar)
                        .addGap(97, 97, 97))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txfPlaca))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfRenavam))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txfChassi))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbPessoasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastroModelo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(cbxVeiculoOficial)))
                        .addContainerGap(85, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPessoasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastroModelo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxVeiculoOficial)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btcCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private Veiculo buscarVeiculoPorPlaca(String placa) {
    try {
        List<Veiculo> veiculos = persistenciaJPA.getEntityManager()
                .createQuery("SELECT v FROM Veiculo v WHERE v.placa = :placa", Veiculo.class)
                .setParameter("placa", placa)
                .getResultList();
        return veiculos.isEmpty() ? null : veiculos.get(0);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao buscar veículo: " + e.getMessage());
        return null;
    }
}
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
  try {
        // Verifica se a placa foi preenchida
        String placa = txfPlaca.getText().trim();
        if (placa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "A placa do veículo é obrigatória!");
            return; // Impede o cadastro se a placa não for preenchida
        }

        // Verifica se a placa já está cadastrada
            Veiculo veiculoExistente = buscarVeiculoPorPlaca(placa);
        if(veiculoExistente != null && (veiculo == null || veiculoExistente.getId() != veiculo.getId())) {
         JOptionPane.showMessageDialog(this, "Já existe um veículo cadastrado com essa placa!");
         return;
     }

      

        // Verifica se é veículo oficial
        boolean isOficial = cbxVeiculoOficial.isSelected();

        // Se o veículo não existe, cria um novo
        if (veiculo == null) {
            if (isOficial) {
                veiculo = new VeiOficial();
                ((VeiOficial) veiculo).setRenavan(txfRenavam.getText());
                ((VeiOficial) veiculo).setChassi(txfChassi.getText());
            } else {
                veiculo = new Veiculo();
            }
        } else {
            // Se o veículo já existe, apenas atualiza
            if (isOficial) {
                ((VeiOficial) veiculo).setRenavan(txfRenavam.getText());
                ((VeiOficial) veiculo).setChassi(txfChassi.getText());
            }
        }

        // Configurações comuns para ambos os tipos
        veiculo.setPlaca(placa);
        veiculo.setCor("Cor"); // Exemplo
        veiculo.setModelo((Modelo) cmbModelo.getSelectedItem());
        veiculo.setProprietario((Pessoa) cmbPessoasCadastradas.getSelectedItem());

        // Persistência no banco de dados
        persistenciaJPA.getEntityManager().getTransaction().begin();
      if (veiculo.getId() == 0) {
            persistenciaJPA.getEntityManager().persist(veiculo); // Cadastro novo
        } else {
            veiculo = persistenciaJPA.getEntityManager().merge(veiculo); // Atualiza o veículo
        }


        persistenciaJPA.getEntityManager().getTransaction().commit();

        JOptionPane.showMessageDialog(this, "Veículo salvo com sucesso!");
        limparCampos();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao salvar o veículo: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSalvarActionPerformed
private void limparCampos() {
   cmbPessoasCadastradas.setSelectedIndex(0);
    cmbModelo.setSelectedIndex(0);
    cbxVeiculoOficial.setSelected(false);
    txfChassi.setText("");
    txfRenavam.setText("");
    }
    private void btcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcCancelarActionPerformed
        // TODO add your handling code here:
         limparCampos();
        dispose();
    }//GEN-LAST:event_btcCancelarActionPerformed

    private void cbxVeiculoOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVeiculoOficialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVeiculoOficialActionPerformed

    private void cmbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbModeloActionPerformed

    private void cmbPessoasCadastradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPessoasCadastradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPessoasCadastradasActionPerformed

    private void btnCadastroModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroModeloActionPerformed
        // TODO add your handling code here:
           TelaCadastroModelo telaModelo = new TelaCadastroModelo();
           telaModelo.setVisible(true);
   
    }//GEN-LAST:event_btnCadastroModeloActionPerformed

    private void txfPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfPlacaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPlacaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcCancelar;
    private javax.swing.JButton btnCadastroModelo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cbxVeiculoOficial;
    private javax.swing.JComboBox<Modelo> cmbModelo;
    private javax.swing.JComboBox<Pessoa> cmbPessoasCadastradas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txfChassi;
    private javax.swing.JTextField txfPlaca;
    private javax.swing.JTextField txfRenavam;
    // End of variables declaration//GEN-END:variables
}
